name: badminton_court_booking
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: 2.3.3
  json_serializable: ^6.6.1
  retrofit_generator: 4.2.0
  injectable_generator: 2.1.3
  # UI
  cupertino_icons: ^1.0.5
  flutter_launcher_icons: ^0.11.0
  collection: ^1.17.0
  google_fonts: ^4.0.3
  flutter_svg: ^2.0.0+1
  settings_ui: ^2.0.2
  shared_preferences: 2.0.17
  phone_number: ^1.0.0
  flutter_spinkit: ^5.2.0

  cached_network_image: ^3.2.3
  fluttertoast: ^8.1.3
  equatable: ^2.0.5
  carousel_slider: ^4.2.1
  shimmer: ^2.0.0
  custom_refresh_indicator: ^2.0.1
  progress_indicators: ^1.0.0
  intl: ^0.17.0


  # Core
  flutter_bloc: 8.1.2
  firebase_core: ^2.5.0
  rxdart: ^0.27.7
  retrofit: 3.3.1
  dio: 4.0.6
  flutter_cache_manager: ^3.3.0
  json_annotation: ^4.8.0
  quiver: ^3.2.1
  get_it: 7.2.0
  universal_io: 2.0.4
  fimber: ^0.6.6
  image_picker: ^1.0.0
  hooks_riverpod: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/lang/
    - assets/icon/
    - assets/icon/emotion/
    - assets/icon/svg/
    - assets/image/
    - assets/image/menu/
    - assets/anim/
    - assets/json/
    - assets/json/response/