// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWiGehWelmcTv3UYhLoT34hwfF-H1SeSg',
    appId: '1:883075458036:web:9c961ba2ba6373eb8d4fa1',
    messagingSenderId: '883075458036',
    projectId: 'mental-health-95f4c',
    authDomain: 'mental-health-95f4c.firebaseapp.com',
    storageBucket: 'mental-health-95f4c.appspot.com',
    measurementId: 'G-FZX203FS77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9eEfrvB0CDMLwp-JBf5uKY3PVO_LsM-0',
    appId: '1:883075458036:android:e4599c9e20dce41d8d4fa1',
    messagingSenderId: '883075458036',
    projectId: 'mental-health-95f4c',
    storageBucket: 'mental-health-95f4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl-tFYaPybnvuP6LssrvBmpmm-Arc0BDw',
    appId: '1:883075458036:ios:ed78f64d123c77518d4fa1',
    messagingSenderId: '883075458036',
    projectId: 'mental-health-95f4c',
    storageBucket: 'mental-health-95f4c.appspot.com',
    iosClientId: '883075458036-0gni8r7c7k2tbn81r8pls2j4cv70r62o.apps.googleusercontent.com',
    iosBundleId: 'com.beacom.mentalHealth',
  );
}
